In [1]:
def hypothesis(self, X,theta):
        '''
            Computes the hypothesis for over given input examples (X) and parameters (thetas).

            Input:
                X: can be either a single n X d-dimensional vector or n X d dimensional matrix
                theta: Must be a d-dimensional vector
            Return:
                The computed hypothesis
        '''
        
        # Your Code here
        return

In [2]:
def cost_function(self, X,Y, theta):
        '''
            Computes the Cost function for given input data (X) and labels (Y).

            Input:
                X: can be either a single n X d-dimensional vector or n X d dimensional matrix of inputs
                theata: must  d X 1-dimensional vector for representing vectors
                Y: Must be n X 1-dimensional label vector
                
            Return:
                Returns the cost of hypothesis with input parameters 
        '''
    
        # Your Code here
        return 
def derivative_cost_function(self,X,Y,theta):
        '''
            Computes the derivates of Cost function w.r.t input parameters (thetas)  
            for given input and labels.

            Input:
            ------
                X: can be either a single n X d-dimensional vector or n X d dimensional matrix of inputs
                theata: must  d X 1-dimensional vector for representing vectors
                Y: Must be n X 1-dimensional label vector
            Returns:
            ------
                partial_thetas: a d X 1-dimensional vector of partial derivatives of cost function w.r.t parameters..
        '''
        return


In [3]:
def gradient_descent(self, X, Y, cost_function, derivative_cost_function):
        '''
            Finds the minimum of given cost function using gradient descent.
            
            Input:
            ------
                X: can be either a single n X d-dimensional vector 
                    or n X d dimensional matrix of inputs            
                
                Y: Must be n X 1-dimensional label vector
                cost_function: a function to be minimized, must return a scalar value
                derivative_cost_function: derivative of cost function w.r.t. paramaters, 
                                           must return partial derivatives w.r.t all d parameters                                                           
                        
            Returns:
            ------
                thetas: a d X 1-dimensional vector of cost function parameters 
                        where minimum point occurs (or location of minimum).
        '''

        # Your Code here
        return thetaes

In [4]:
def train(self, X, Y, optimizer):
        ''' Train classifier using the given 
            X [m x d] data matrix and Y labels matrix
            
            Input:
            ------
            X: [m x d] a data matrix of m d-dimensional examples.
            Y: [m x 1] a label vector.
            optimizer: an object of Optimizer class, used to find
                       find best set of parameters by calling its
                       gradient descent method...
            Returns:
            -----------
            Nothing
            '''
        
        # Your Code here 
        return

In [5]:
def predict(self, X):
        
        """
        Test the trained Logistic Regression result on the given examples X
        
                   
            Input:
            ------
            X: [m x d] a matrix of m  d-dimensional test examples.
           
            Returns:
            -----------
                pclass: the predicted class for the given set of examples, i.e. to which it belongs
        """
        # Your Code here
        return

In [107]:
import pandas as pd
DataSet = pd.read_csv("OnlineNewsPopularity\OnlineNewsPopularity.csv")

In [108]:
DataSet.head()

url   timedelta  \
0  http://mashable.com/2013/01/07/amazon-instant-...       731.0   
1  http://mashable.com/2013/01/07/ap-samsung-spon...       731.0   
2  http://mashable.com/2013/01/07/apple-40-billio...       731.0   
3  http://mashable.com/2013/01/07/astronaut-notre...       731.0   
4   http://mashable.com/2013/01/07/att-u-verse-apps/       731.0   

    n_tokens_title   n_tokens_content   n_unique_tokens   n_non_stop_words  \
0             12.0              219.0          0.663594                1.0   
1              9.0              255.0          0.604743                1.0   
2              9.0              211.0          0.575130                1.0   
3              9.0              531.0          0.503788                1.0   
4             13.0             1072.0          0.415646                1.0   

    n_non_stop_unique_tokens   num_hrefs   num_self_hrefs   num_imgs   ...     \
0                   0.815385         4.0              2.0        1.0   ...      
1                   0.791946         3.0              1.0        1.0   ...      
2                   0.663866         3.0              1.0        1.0   ...      
3                   0.665635         9.0              0.0        1.0   ...      
4                   0.540890        19.0             19.0       20.0   ...      

    min_positive_polarity   max_positive_polarity   avg_negative_polarity  \
0                0.100000                     0.7               -0.350000   
1                0.033333                     0.7               -0.118750   
2                0.100000                     1.0               -0.466667   
3                0.136364                     0.8               -0.369697   
4                0.033333                     1.0               -0.220192   

    min_negative_polarity   max_negative_polarity   title_subjectivity  \
0                  -0.600               -0.200000             0.500000   
1                  -0.125               -0.100000             0.000000   
2                  -0.800               -0.133333             0.000000   
3                  -0.600               -0.166667             0.000000   
4                  -0.500               -0.050000             0.454545   

    title_sentiment_polarity   abs_title_subjectivity  \
0                  -0.187500                 0.000000   
1                   0.000000                 0.500000   
2                   0.000000                 0.500000   
3                   0.000000                 0.500000   
4                   0.136364                 0.045455   

    abs_title_sentiment_polarity   shares  
0                       0.187500      593  
1                       0.000000      711  
2                       0.000000     1500  
3                       0.000000     1200  
4                       0.136364      505  

[5 rows x 61 columns]

In [109]:
size = DataSet.shape
last_column_index = size[1]
X = DataSet.iloc[:,2:last_column_index-1].values    #Extract all rows and all Columns execpt first two columns
Y = DataSet.iloc[:, last_column_index-1].values     #Extract Dependent Variable

In [110]:
Y

array([ 593,  711, 1500, ..., 1900, 1100, 1300], dtype=int64)

In [112]:
X[0]

array([ 1.20000000e+01,  2.19000000e+02,  6.63594467e-01,  9.99999992e-01,
        8.15384609e-01,  4.00000000e+00,  2.00000000e+00,  1.00000000e+00,
        0.00000000e+00,  4.68036530e+00,  5.00000000e+00,  0.00000000e+00,
        1.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  4.96000000e+02,  4.96000000e+02,
        4.96000000e+02,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  5.00331204e-01,  3.78278930e-01,  4.00046751e-02,
        4.12626477e-02,  4.01225435e-02,  5.21617145e-01,  9.25619835e-02,
        4.56621005e-02,  1.36986301e-02,  7.69230769e-01,  2.30769231e-01,
        3.78636364e-01,  1.00000000e-01,  7.00000000e-01, -3.50000000e-01,
       -6.00000000e-01, -

In [119]:
import numpy as np
#Simple Normaliztion 
def Normaliztion(x):
    X_normal = x
    M = np.zeros((1,last_column_index))
    S = np.zeros((1,last_column_index))
    #convert the x features into numpy matrix
    newx = np.matrix(x)
    # find the mean and the standard diviation of the features
    M = newx.mean(0)       #Mean Column vis
    print(M)
    S = newx.std(0)
    X_normal =  np.divide(np.subtract(x , M), S)
    return X_normal , M , S

In [120]:
# initialize the mean and std matrix
MEAN = np.zeros((1,last_column_index))
STD  = np.zeros((1,last_column_index))
#call the method Normaliztion and gets the new dependent features
X, MEAN, STD = Normaliztion(X)

[[ 3.44123210e-17 -4.12230928e-18  0.00000000e+00 -3.58461677e-19
   0.00000000e+00 -2.29415473e-17 -5.73538683e-18 -5.73538683e-18
   6.45231018e-18  1.14707737e-17  0.00000000e+00  1.72061605e-17
   0.00000000e+00 -3.44123210e-17  3.44123210e-17  2.00738539e-17
   5.73538683e-18  2.29415473e-17 -1.43384671e-18 -5.73538683e-18
   5.73538683e-18 -1.60590831e-16  2.29415473e-17 -5.73538683e-18
   3.58461677e-18  8.60308024e-18  1.43384671e-18 -1.43384671e-18
   5.73538683e-18 -9.60677294e-17  7.16923354e-18  5.50238674e-17
   1.05387733e-16  1.93569305e-17 -8.17292623e-17  4.37323246e-17
   9.03323426e-17  1.14707737e-17 -8.60308024e-18 -2.86769341e-17
   3.87138611e-17  4.58830946e-17  0.00000000e+00  0.00000000e+00
   0.00000000e+00 -2.00738539e-17  0.00000000e+00 -1.18292353e-17
   2.29415473e-17  1.72061605e-17  5.73538683e-18 -8.60308024e-18
   6.45231018e-18  2.86769341e-18 -7.16923354e-19 -1.29046204e-17
   1.03953886e-17 -1.50553904e-17]]


In [66]:
DataSet.describe()

timedelta   n_tokens_title   n_tokens_content   n_unique_tokens  \
count  39644.000000     39644.000000       39644.000000      39644.000000   
mean     354.530471        10.398749         546.514731          0.548216   
std      214.163767         2.114037         471.107508          3.520708   
min        8.000000         2.000000           0.000000          0.000000   
25%      164.000000         9.000000         246.000000          0.470870   
50%      339.000000        10.000000         409.000000          0.539226   
75%      542.000000        12.000000         716.000000          0.608696   
max      731.000000        23.000000        8474.000000        701.000000   

        n_non_stop_words   n_non_stop_unique_tokens     num_hrefs  \
count       39644.000000               39644.000000  39644.000000   
mean            0.996469                   0.689175     10.883690   
std             5.231231                   3.264816     11.332017   
min             0.000000                   0.000000      0.000000   
25%             1.000000                   0.625739      4.000000   
50%             1.000000                   0.690476      8.000000   
75%             1.000000                   0.754630     14.000000   
max          1042.000000                 650.000000    304.000000   

        num_self_hrefs      num_imgs    num_videos      ...        \
count     39644.000000  39644.000000  39644.000000      ...         
mean          3.293638      4.544143      1.249874      ...         
std           3.855141      8.309434      4.107855      ...         
min           0.000000      0.000000      0.000000      ...         
25%           1.000000      1.000000      0.000000      ...         
50%           3.000000      1.000000      0.000000      ...         
75%           4.000000      4.000000      1.000000      ...         
max         116.000000    128.000000     91.000000      ...         

        min_positive_polarity   max_positive_polarity   avg_negative_polarity  \
count            39644.000000            39644.000000            39644.000000   
mean                 0.095446                0.756728               -0.259524   
std                  0.071315                0.247786                0.127726   
min                  0.000000                0.000000               -1.000000   
25%                  0.050000                0.600000               -0.328383   
50%                  0.100000                0.800000               -0.253333   
75%                  0.100000                1.000000               -0.186905   
max                  1.000000                1.000000                0.000000   

        min_negative_polarity   max_negative_polarity   title_subjectivity  \
count            39644.000000            39644.000000         39644.000000   
mean                -0.521944               -0.107500             0.282353   
std                  0.290290                0.095373             0.324247   
min                 -1.000000               -1.000000             0.000000   
25%                 -0.700000               -0.125000             0.000000   
50%                 -0.500000               -0.100000             0.150000   
75%                 -0.300000               -0.050000             0.500000   
max                  0.000000                0.000000             1.000000   

        title_sentiment_polarity   abs_title_subjectivity  \
count               39644.000000             39644.000000   
mean                    0.071425                 0.341843   
std                     0.265450                 0.188791   
min                    -1.000000                 0.000000   
25%                     0.000000                 0.166667   
50%                     0.000000                 0.500000   
75%                     0.150000                 0.500000   
max                     1.000000                 0.500000   

        abs_title_sentiment_polarity         shares  
count                   39644.00000

In [105]:
X[0]

matrix([[ 7.57447233e-01, -6.95210448e-01,  3.27718727e-02,
          6.75074648e-04,  3.86578580e-02, -6.07462593e-01,
         -3.35566105e-01, -4.26525775e-01, -3.04268192e-01,
          1.56474152e-01, -1.16482069e+00, -2.36445017e-01,
          2.14887984e+00, -4.32947848e-01, -2.49487028e-01,
         -4.76911337e-01, -5.19566229e-01, -3.74923515e-01,
         -2.99110670e-01, -5.03187845e-01, -2.34755267e-01,
         -3.50734772e+00, -1.91917761e+00, -9.82156467e-01,
         -9.27594897e-01, -2.37901396e+00, -1.77458739e-01,
         -2.39676274e-01, -2.43925944e-01,  2.22523233e+00,
         -4.78663628e-01, -4.80454058e-01, -4.73760968e-01,
         -4.09826850e-01, -2.56820594e-01, -2.72322187e-01,
         -3.88118062e-01,  1.20063309e+00,  1.07882676e+00,
         -6.24921186e-01, -6.18275745e-01, -6.70540635e-01,
          6.70593243e-01, -2.75945948e-01,  3.46403242e-01,
         -2.69078506e-01,  4.57827291e-01, -3.66076587e-01,
          2.37337037e-01,  6.38648774e-0